language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: b4SoRkTwSw08z/Yyd+RSHYNWtRf4VWP7dH7NXeadsfmro/nU7UWErBf0cO9Y+0SXKTFuTd7bxgx80hHcCahNAUYZ4QPJxfzbe7DxWI4D2im92ca1EecfkFZQu8bk40atCNkf0W8fZbZTmr24jcWLjoCA0H6IuilpFxRLwVXZLDD/En+nxuFbq6VUCCdg+bPAg80GFzKVKcH8BsR2DqC5rUx6EoW7UgY+wDmkMx4TwVFkHIzINBrYgT3JP0GpYynYiskTrsWbkoJokurouPXNngHP1KNM7+2vZH4wlv/i4+kLkM0CZ6FukmAKDDHt17q/JRx/DzblzNsvDtLAhWxhlyy5Uh5GXXWNP92xr76c3WVke/b5Yb6tghrxBKREZFpWvYRIPpulNDaQUrbwsX3rNDNASr6ammOjmQ1YyJppZvZekIP3RZcFUS73gfIbdrAAJ493kfYCIhDwE2rZMNBAe0qM9jion0Tz+6S5PtTJRbbhn2WGic6NCUgr44ilQ+zQ6BFBU/jCejzujcDX0LU8rUJUOU+1lN9DcKg9bS06xnuX3Xm0+pG6vH1vnssW2mnOtxFGAZInizGe3f3tloixnpi8xFZdIR6XurgD+Dkq29pCXE9w82rr5UOEn59PmU70WDO5DExJYpLFRvOA7kxNbRwDez5OhKsLc3YdHk9xaSk=
  app: enigmatic-bastion-91345
  on:
    repo: mike31415/mongoose-blog-ci
