language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Xt5Xwu8kZE21kyRr7OS9xs5Zgecu1X3evb9fGskV3W/DhCuQApRa090VlDMnaNrkV2zrzG/pRryYweqMguSL0QSVveIEHycByFXpGF6WvogL0ARH9hyw7DiFbos+oohvu2+3iTwfExm9owePb5LN7ZCUfgi9ySV8oKwD773iFvtXJksk2FddgG2IDTKSwHJxtChGRzQqkDFosD+pcNa1z/1iXAJfEzEAP09y3kK0beu621cd6LOKrrY7tYZrLsIiR5m0CROQScXK4dMzby+CpSFJ0sNF9mDGzqC+dHg1V/M2mdwh4IaKkh/CZ8deFijNYDC0KiOVAjRiqd9ichamuNdGmu2GjrIlpe0UiY8olA+SOS3G/5zLhY2GO4/MzbdNFqc+JgrYuT0j6Yu8PMV09qruRTAkeeVfPP3t5K9Zgsfjdx5vXj7TiSOlNQw7uHBghStwPMnDyh3o3e7C+qR3rhpdl2yEJp9zXmPQZmSkUsICAlt9dJSx0pCUTCJ7tu4haN+DOP0ggGN650bg2BaAG8H7c8xKnWf3cBh85RTCDIZpMPoGgC+5dZwn6G9RsUIK9ZsEzs+SHGMVSxE+lYnFTIXZuboqMIotdlKv4w0WfNPNnBYdYDs8ircTsrmGYLjW54VcUY0qcHkEnmfvIomhDS6Q5QnwD+geUqChvES6Gi8=
  app: enigmatic-bastion-91345
  on:
    repo: mike31415/mongoose-blog-ci
secure: "C68d2XBGknm0+Cz3A3Wmeh26J9mMkcAau97CnkaNUE+9MBmg2aw0TiyApD0s27d/DWGlbaN03kjDXhRYhHPCaNtCx7TgaJhe+yLhfDSbGa/O1BDDWPywnVUqX+ZVQnpCn/jHJeVGgnfIqtiUHZHASMkKaM85jfkV39o8/8Pm9R6CLAJ3CXqgz5Uu8kRLppMtHvOZhLhHxdhYfndSZ/FZ4ANSzuAJ9PtI1ceOhZI/BVllSckDHSnGXnvAs7wWkE7Lfvc1KUa7jpHXbNyq/qpzB0UsIV/ORplbB+HzQ2xXm8smcyHwoEFP0HSGKpqPfZdlaJ5au2tHS3W01sWgHbOQot9LsptvQf4pznTFaaxLMLBgP7gUa4XzHpMF0kPSgbB+Xvsm0bAP/JzvJElQL2pp69kexBHWrhYB1cbkxdX0N/n+zz8JeUKFZE/oKmveP+1nokqTut1ktgCWyXM4sVV2r8h/y3eIiA81RShiJirKNxLJlgQ8dO3M9LEjkhp9xEpDIakC2DNX0SHn/3P2J4eYoGqJ+7byX91itezmCQTlBYFUQx5pgp/iKuVUN1/V/6e5jxDtiDJNgHtEr099t72CLn+eyDblpNHZTuXl3LWHBSmUXQd/ea6gDgmVF+3kAizOc4QupBV1XNp5srJ+8MkFfNwk0a62C0B0XfS76NUJodk="
